name = "reeeeecallstudy"
compatibility_date = "2025-01-01"
main = "worker.ts"

[assets]
directory = "dist"
binding = "ASSETS"
html_handling = "auto-trailing-slash"
not_found_handling = "single-page-application"
